import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/services/AuthProvider";
import NextUIWrapper from "@/components/NextUIWrapper";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full bg-[url(/gradient-bg.png)] min-h-screen dark`}>
        <NextUIWrapper>
          <AuthProvider>
          {children}
          </AuthProvider>
          <Toaster
  position="top-right"
  reverseOrder={true}
/>
        </NextUIWrapper>
        </body>
    </html>
  );
}
